build:
  environment:
    php:
      version: '7.4'
  nodes:
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover tests/coverage/coverage-clover.xml
            coverage:
              file: tests/coverage/coverage-clover.xml
              format: clover
filter:
  excluded_paths: [vendor/*, tests/*]