build:
  nodes:
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover tests/coverage/coverage.clover
            coverage:
              file: tests/coverage/coverage.clover
              format: clover