build:
  nodes:
    my-tests:
      environment:
        php:
          version: 7.4
    coverage:
      tests:
        override:
          - command: php ./vendor/bin/phpunit --coverage-clover tests/coverage/coverage.clover
            coverage:
              file: tests/coverage/coverage.clover
              format: clover
filter:
  excluded_paths: [vendor/*, tests/*]